# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d84f6de8026a21f80b4db51234033ca73b762966823d8b9c8cbc2317b14b35665b777b57b0f0fc4267493f9cacf3390462e6e7120047d9287b32a29769f66ae

test:
  secret_key_base: fba125c2dc16121223367babb169b81b66d4a128a07fb2bb6046e1cd0ceedfe34226912aa1efc61f28799237faac5e41418c31b05d0c45477cc8e856736f96be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
